### PR TITLE
Revert a2md change, more bug fixes

### PR DESCRIPTION
**Pull request by tlhackque**
This change to `a2md` was cherry-picked from another branch.  It relies on support elsewhere in the codebase.

I thought I'd previously backported that support - but I haven't.  It's not worth doing at this point.

@icing's patch disabled the function, but left the switches and documentation. 

This completely reverts the change to `a2md` for master.  It will return when we merge the other branch.

Sorry for the confusion.

### CODE REVIEW

**Comment by tlhackque** [comment]
Another round (mostly) with Pebble, cherry picked from another branch:
 - This should fix the remaining Content-Type header issues - allowing cert downloads from Pebble.
 - V2 should not be sending keyAuthorization in challenge response
 - The status display would never display "finished"

Made sure to build master this time :-)

**Comment by tlhackque** [comment]
Still chasing Pebble mayhem...

**Comment by icing** [comment]
All tests running fine! :-D

**Comment by tlhackque** [comment]
Thanks for the testing and the merge.  I'm **still** chasing Pebble - it's done a good job of being "not Boulder" :-)  So there's more to come.  I'll also look at #216 - unless you are working on it.

**Comment by icing** [comment]
Please feel free to go ahead! I am rather busy with customer things these days.

**Pull request merged**
