### PR TITLE
[WIP] Fixes & issues for 2.3.0

### PR DESCRIPTION
**Pull request by tlhackque**
I updated one of my simpler configs with 2.3.0 Beta (actually, from master).  It had never run `mod_md` before.

It mostly works, but of course I found a few divotsL:

I will add commits and comments here as I debug.

## Fixed:
 - filename lowercasing assumed apr_tolower() works on a string; it works on a single character.
 - The `Check@` column of **Managed Certificates** status is hard to read with more than one key type..  I added a break
 - With any significant number of names, the other columns of te **Managed Certificates** table become compressed.  I added a limit that seems reasonable - it can be tuned.
 - Fallback certificates were only created for RSA, not all those specified in `MDPriivateKeys`
 - /.httpd/certificate-status contains only the RSA cert status, nothing on the EC
## Open:
 - SeLinux issues left staging area with incorrect permissions.  When fixed, `mod_md` did not recover.  I deleted the ServerRoot/md tree - but perhaps `mod_md` should recover.  In any case, the logging did not point me to the files/directories that were blocked.
 - The OCSP status is hard for humans to make sense of.  The certificate ID is a poor identifer.  Can we at least add the key type or (better) the CN (or first SAN if no CN)?
 - I had to delete the certificates database directories as well as stop/start `httpd` to switch from staging to the live LE certificates.  "graceful" did not suffice.

The `mod_md` config is quite simple:
````
  21: MDCertificateAuthority "https://acme-v02.api.letsencrypt.org/directory"
  23: MDCertificateProtocol "ACME"
  24: MDCertificateAgreement "accepted"
  26: MDPortMap http:-
  27: MDCAChallenges tls-alpn-01
  35: MDPrivateKeys RSA 4096 P-384
  36: MDRenewMode auto
  38: MDStapling on
  39: MDStapleOthers on
  41: MDServerStatus on
  43: MDCertificateStatus on
  59: MDContactEmail "security+md-wiki@litts.net"
  62: <MDomain wikiworld.litts.net>
  63:   MDMembers auto
    : </MDomain>
````
(There is also a `Protocols` directive including `acme-tls/1`)

More later.

### CODE REVIEW

**Comment by tlhackque** [comment]
I've added a commit to generate and provide fallback certificates for all requested key types.
Hint: easier to review if you hide whitespace changes.

**Comment by tlhackque** [comment]
Updated /.httpd/certificate-status to provide info for each certificate.
Data under "renewal" has not been tested, but should work.

**Comment by tlhackque** [comment]
Not sure if I'll have any more time this weekend...feel free to merge what I have.  I can always open another pull request.

**Comment by icing** [comment]
Hi Timothe, nice work! I'll merge and test locally. When all is fine, I release a v2.3.1 with it, so more people can pick this up and try it out.

Have a good weekend.

**Comment by tlhackque** [comment]
Thanks for the additional work and prompt release.  More testing is always better!

**Pull request merged**
