### PR TITLE
[WIP] 2.3.1 divots/fixes

### PR DESCRIPTION
**Pull request by tlhackque**
Divots found in 2.3.1

## Fixed
 - Certs (fallback & tls-alpn-01) attributes wrong/missing.
    - `BasicConstraints`: when `CA:false` is set, the `pathlen` attribute **must** be omitted
    - `BasicConstraints`: mark `critical`
    - `keyUsage` and `extKeyUsage`: set for server authentication (satisfy picky clients)
 - `iPAddress` in GeneralNames is an ASN1 _octet string_ (not _ia5_ as code assumed).

## Open
 - Carry-forward from #185 
 - Full support for iPAddress in subject/SANs needs thought/work - see commit notes.

Will add more & update as/if time permits.

### CODE REVIEW

**Comment by icing** [comment]
Wow, quite some collection!

For the things that have their own repository, I'd rather point to them than include copies here. I do not want to keep them up-to-date manually, do you?

I'll merge this in and let the tests run.

**Comment by icing** [comment]
The `#ifdef __GNUC__` do not work in clang, I'll remove them.

**Comment by tlhackque** [comment]
> For the things that have their own repository, I'd rather point to them than include copies here. I do not want to keep them up-to-date manually, do you?

I agree, mostly.  OTOH, they are quite stable - more seem to get added, but what's there historically hasn't changed.  It's a starting point - and annoying when one has to get dependencies in order to get started.

Many of them have hard-coded passwords or need other local customizations.  Note that I don't install them.  We can't test them all - we'd need an account on each provider.  The thought process was to provide something "AS-IS" to get people started.  The wrapper functions in `md_events` help.

One approach would be for your build to just get the latest copy of that directory.  The README for that directory says "snapshot", "as-is".

Mostly I wanted you to have something to play with in the short term while we come up with MDEvent.  Distribution and/or update seems like something to think about another day...

**Comment by tlhackque** [comment]
> The `#ifdef __GNUC__` do not work in clang, I'll remove them.

I wondered whether about that - don't have clang.  OTOTH, didn't know if all other compilers would support the __attributes - hopefully autotools defines null expansions.

I was annoyed that --enable--werror used the fallthrough warning level that requires the __attributes instead of obeying the structured comments...

**Comment by icing** [comment]
`--werror` is currently a race to the bottom. compilers are continously improving the analyzer and in their greed to have more than others, they go overboard. I guess we need to go over the -W flags that we use and disable those the keep on doing things we do not want. 

In this case, I find a switch fallback with a comment totally readable and nice. Adding #pragma or compile specific workarounds hinders this readability.

**Comment by tlhackque** [comment]
Agree 100%.  I'm not an autotools person, so I did what I could to help the user quickly.

-wimplicit-fallthrough=4 would be fine - the issue here is that level 5 turns off the structured comments.  --werror enables level 5.

werror is useful for developers because it makes us look at the issues.  For end users, it creates a lot of false positives - I don't recommend it to them.

**Comment by tlhackque** [comment]
I added a commit to enable `-Wimplicit-fallthrough=3` with -werror in configure for gcc.

This restores the checks and parses the existing comments.

(It turns out that clang accepts the "=3" in configure, but rejects it when actually compiling.)

I also added a best-efforts attempt to display the compiler version; that may
help with future issues.

**Pull request merged**
