### PR TITLE
Fix build issue with LibreSSL

### PR DESCRIPTION
**Pull request by Sp1l**
Import missing functions and struct from OpenSSL 1.0.2

Not sure if you wish to support this and how that should be included in your code. This works-for-me(TM)

This was just commited to FreeBSD ports as a new port. freebsd/freebsd-ports@854b76e585531c1d1f740d272ff9cff11751c8e9

### CODE REVIEW

**Comment by icing** [comment]
If I read it correctly, its all about a missing ```ASN1_TIME_diff()```?

**Comment by icing** [comment]
And thanks for making it available via your ports!

**Comment by Sp1l** [comment]
Looong delay, but yes this is about the missing `ASN1_TIME_diff()`

**Comment by icing** [comment]
I do not really like this. If libressl does not want to maintain that openssl code in their lib, Apache httpd is the wrong place to keep a copy of it. Don't you agree?

I am looking for a way around this....

**Comment by icing** [comment]
Can you check if current master solves the problem? Thanks!

**Comment by Sp1l** [comment]
That almost builds. Only ran into an issue with `SSL_get0_key` and `NID_tlsfeature` which are not available in LibreSSL. These were already in a compat block for OpenSSL 1.1 so added an ifdef conditional there.
Built OK with this patch.

**Comment by icing** [comment]
Great!

**Pull request merged**
