### PR TITLE
Catch up with TL

### PR DESCRIPTION
**Pull request by tlhackque**
This includes several fixes for issues encountered during testing/development.

### CODE REVIEW

**Comment by icing** [comment]
Looks good from the diffs. Taking it in and seeing what it does in my local test env.

**Comment by icing** [comment]
The md_config_get_trusted call from md_curl seems to be missing, commenting that out. werror fails as function is not previously declared.

Besides that, test run fine. \o/

**Comment by tlhackque** [comment]
It's not unused.  md_curl calls it, and there is a parallel routine in mod_md_config that works from the MDTrustedCAfile and MDTrustedCApath directives.  

This was all in my last pull request - it seems that some parts were dropped in the merge.

I'll create a new pull request as soon as I restore the missing pieces.

**Comment by tlhackque** [comment]
My fault.  I thought I'd cherry-picked that from my other branch, but I did not.

I'll revert & issue a new pull request.  The change to a2md can wait till we merge the other branch...

Sorry.

**Pull request merged**
